# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_number',
            name='phone_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
